-- MySQL Script generated by MySQL Workbench
-- Tue Jul 19 01:57:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema h8
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `h8` ;

-- -----------------------------------------------------
-- Schema h8
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `h8` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `h8` ;

-- -----------------------------------------------------
-- Table `h8`.`clube`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `h8`.`clube` (
  `id` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(35) NOT NULL,
  `email` VARCHAR(35) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `fax` VARCHAR(15) NULL DEFAULT NULL,
  `imagem` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `h8`.`jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `h8`.`jogador` (
  `id` INT NOT NULL,
  `clubeId` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `jogador_clubeId_fkey` (`clubeId` ASC),
  CONSTRAINT `jogador_clubeId_fkey`
    FOREIGN KEY (`clubeId`)
    REFERENCES `h8`.`clube` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `h8`.`clube`
-- -----------------------------------------------------
START TRANSACTION;
USE `h8`;
INSERT INTO `h8`.`clube` (`id`, `pais`, `nome`, `email`, `telefone`, `fax`, `imagem`) VALUES (1, 'Brasil', 'Botafogo', 'botafogo@gmail.com.br', '997160011', NULL, NULL);
INSERT INTO `h8`.`clube` (`id`, `pais`, `nome`, `email`, `telefone`, `fax`, `imagem`) VALUES (2, 'Brasil', 'Corinthians', 'timao@gmail.com.br', '32396699', NULL, NULL);
INSERT INTO `h8`.`clube` (`id`, `pais`, `nome`, `email`, `telefone`, `fax`, `imagem`) VALUES (3, 'Brasil', 'Santos', 'santos@terra.com.br', '997450022', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `h8`.`jogador`
-- -----------------------------------------------------
START TRANSACTION;
USE `h8`;
INSERT INTO `h8`.`jogador` (`id`, `clubeId`, `nome`, `email`) VALUES (1, 3, 'Lionel Messi', 'messi@barcelona.com');
INSERT INTO `h8`.`jogador` (`id`, `clubeId`, `nome`, `email`) VALUES (2, 3, 'Cristiano Ronaldo', 'r7@realmadri.com');
INSERT INTO `h8`.`jogador` (`id`, `clubeId`, `nome`, `email`) VALUES (3, 3, 'Robert Lewandowski', 'lewandowski@bayern.com');
INSERT INTO `h8`.`jogador` (`id`, `clubeId`, `nome`, `email`) VALUES (4, 3, 'Kylian Mbappé', 'kylian@psg.com');
INSERT INTO `h8`.`jogador` (`id`, `clubeId`, `nome`, `email`) VALUES (5, 3, 'Neymar Junior', 'neymar@psg.com');

COMMIT;

